
%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of .train_random_forest() of /model.py

    participant p1 as train_random_forest()<br>:model.py
    participant p2 as <br>:model.py


	p1 ->>+ p2: 1: preprocessing(X)
	p2 -->>- p1: 1: return value
        